FROM python:3.9

RUN mkdir /task

WORKDIR /task

# For Pytest to work well in remote explorer
RUN mkdir -p .vscode
COPY .vscode/remote-settings.json ./.vscode/settings.json

COPY Pipfile Pipfile.lock ./

RUN pip install pipenv && pipenv install --system --deploy

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]