version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - dynamodb
    volumes:
      - "./app:/task/app"
    command: "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
    volumes:
      - dynamodb-data:/home/root/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/root/data"
    user: root
volumes:
  dynamodb-data:
